name: "nuxflare deploy"

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/cache@v4
        with:
          path: |
            .sst
          key: ${{ runner.os }}-sst

      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile
      

      - name: Deploy with SST.dev
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          SST_STAGE=${GITHUB_REF_NAME} pnpm exec nuxflare deploy
